config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :players
root :to => 'players#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :set_player, :only =>[:show, :edit ,:update,:destroy]
	#每次進到controller先跑一次 

	def set_player
		@player = Player.find(params[:id])
	end

	def index
		@players = Player.page(params[:page]).per(5)
		
		if params[:id]
			@player = Player.find(params[:id])
			@sub = "Update"
		else
			@player = Player.new
			@sub = "new"
		end
	end

	def new
		@player = Player.new
	end

	def create
		@players = Player.page(params[:page]).per(5)
		if params[:id] != nil
			@player = Player.find(params[:id])
			@player.update(player_params)
			@player.save
		else
			@player = Player.new(player_params)
		end
		
  		if @player.save
  			flash[:notice] = "player was successfully created"
  			redirect_to :action => :index
  		else
  			flash[:alert] = "player created failed"
  			render :action => :index
  		end
	end

	def show
		#@player = Player.find(params[:id])
	end

	def edit
		#@player = Player.find(params[:id])
		@page = params[:page].to_i 
	end

	def update
		#@player = Player.find(params[:id])
  		@players = Player.page(params[:page]).per(5)
  		if @player.update(player_params)
  			flash[:notice] = "player was successfully updated"
  			@page = params[:page].to_i
  			redirect_to players_path(:page => @page)
  		else
  			flash[:alert] = "player updated failed"
  			render :action => :index
  		end

	end

	def destroy
		#@player = Player.find(params[:id])
  		@player.destroy
  		@page = params[:page].to_i 
  		redirect_to players_path(:page => @page)
	end

	private

	def player_params
  		params.require(:player).permit(:name, :rank,:age,:birth_day)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>World's Badminton Player</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  
    <body>
    <div class="container">
      <div class="row">        
        <div class="col-md-12">
          
          <% if flash[:notice].present?%>
            <div class="alert alert-success" role="alert"> 
              <%= flash[:notice] %> 
            </div>
          <%end%>
          
          <% if flash[:alert].present?%>
            <div class="alert alert-danger" role="alert"> 
             <%= flash[:alert] %> 
            </div>
          <%end%>
          
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/players/_form.html.erb
<% if @player.errors.any? %>
      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <p>Why Failed?: <%= msg %></p>
      <% end %>
      </ul>
<% end %>

<div class="form-group">
	<%= f.label :name,"Name" %>
	<%= f.text_field :name ,:class => "form-control"%>
		
</div>

<div class="form-group">
    <%= f.label :rank, "rank" %>
    <%= f.text_area :rank ,:class => "form-control"%>
</div>

app/views/players/edit.html.erb
<%= form_for @player, :url => player_path(@player),:method =>:patch do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" ,:class => "btn btn-primary"%>
<% end %>

app/views/players/index.html.erb
<h1>World Badminton Players</h1>
<table class="table table-striped" >


Players Name
<tr>
<% @players.each do |player| %>
	<td><%= player.name %></td>
	<td>
  	<%= link_to 'Show' ,  player_path(player) ,:class => "btn btn-info"%>
 	<%= link_to 'Edit',  players_path(:id => player.id,:page => params[:page]) ,:class => "btn btn-primary" %>
 	<%= link_to 'Delete', player_path(player , :page => params[:page]), :method => :delete, :data => { :confirm => "Are you sure?"}, :class => "btn btn-danger" %>
  </td>
  </tr>
<% end %>
</table>
<%= paginate @players %>

<p>Please register your favorite player below </p>

<%= form_for @player do |f| %>
	<div class="form-group">
		<%= f.label :name,"Name" %>
		<%= f.text_field :name ,:class => "form-control"%>		
	</div>

	<div class="form-group">
	    <%= f.label :rank, "Rank" %>
	    <%= f.text_area :rank ,:class => "form-control"%>
	</div>

	<div class="form-group">
	    <%= f.label :age, "Age" %>
	    <%= f.text_area :age ,:class => "form-control"%>
	</div>
	
	<div class="form-group">
	    <%= f.label :birth_day, "Birth Day" %>
	    <%= f.date_select :birth_day ,:class => "form-control"%>
	</div>


    <%= f.submit @sub, :class => "btn btn-primary"%>
<% end %>

app/views/players/new.html.erb
<h1>"New Player"</h1>

<%= form_for @player, :url =>  players_path, :method => :post  do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create"  ,:class => "btn btn-primary"%>
<% end %>

app/views/players/show.html.erb
<h1> <%= @player.name%> 's profile</h1>

<p> Name : <%= @player.name %> </p>
<p>	Rank : <%= @player.rank %></p>
<p>	Age  : <%= @player.age %></p>
<p>	Birth Day  : <%= @player.birth_day %></p>
<p><%= link_to 'Back to index', players_path ,:class => "btn btn-primary"%></p>